### ISSUE TITLE
MagicMirror stays black

### ISSUE THREAD

**Issue by LeeChristmas93** [Eunanibus/MMM-Globe#2] opened 2017-06-05 18:36 UTC
Hi, my problem as mentioned in the title is, that if I start the MagicMirror via "npm start" in the MagicMirror Folder my monitor goes black. I tried without the module and all works fine. 
I noticed that there was no helper found for MMM-Globe, is that correct?
There is even no "Starting module: MMM-Globe" but I added the module in the config.js as mentioned in the readme.
Please help, sorry I'm new to this whole thing, but I want to get that really amazing looking Module! :)

**Comment by Eunanibus** [comment] 2017-06-06 09:49
Hi Lee.

The problem with identifying particular issues is that we need to see the log file and your general environment to get a better idea of what is going on to help you.

The best way to get your queries answered is to post them [in this forum link](https://forum.magicmirror.builders/topic/2553/mmm-globe/30) where we can assist you further. 

Try to give as much information as possible. I have recognised that a few Pi users are having issues with this module due to the excessive computational power needed, but this is simply a hardware issue as opposed to a development one. The best way to isolate the issue is to debug it, but in the forum post above, a few other users have mentioned an issue similar to yours which was resolved by turning on 3GL rendering on their machine.

**Closed as completed by Eunanibus** 2017-06-06 09:49 UTC
